version: 2
jobs:
  build-go:
    docker:
      - image: circleci/golang:1.13
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/hashicorp-demoapp/public-api
    steps:
      - checkout
      - run:
          name: install dependencies
          command: go get -u golang.org/x/sys/...
      - run:
          name: test application
          command: go test -v ./...
      - run:
          name: build application (linux amd64)
          command: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/amd64/public-api
      - run:
          name: build application (linux arm64)
          command: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o bin/arm64/public-api
      - persist_to_workspace:
          root: /go/src/github.com/hashicorp-demoapp
          paths:
            - public-api
  
  functional-tests:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: curl https://shipyard.run/install | bash -s
      - run:
          name: build dev docker container
          command: make build_docker_dev
      - run:
          name: run functional tests with Shipyard
          command: cd functional_test && shipyard test



  publish-docker-release:
    docker:
      - image: circleci/golang:1.13
    environment:
      GO111MODULE: "on"
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    working_directory: /go/src/github.com/hashicorp-demoapp/public-api
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /go/src/github.com/hashicorp-demoapp
      - run:
          name: install docker buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64"

            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"

            mkdir -p ~/.docker/cli-plugins

            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx

            docker buildx install

            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"

            docker context create multi_arch_build

            # Create Builder
            docker buildx create --use multi_arch_build
      - run:
          name: docker login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: docker buildx build and push
          command: |
            docker buildx build --platform linux/amd64,linux/arm64 \
              -t hashicorpdemoapp/public-api:${CIRCLE_TAG} \
              --push \
              .

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/go/src/github.com/hashicorp-demoapp/public-api
    steps:
      - attach_workspace:
          at: ~/go/src/github.com/hashicorp-demoapp
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -replace ${CIRCLE_TAG} ./bin/

workflows:
  version: 2
  build-and-release:
    jobs:
      - build-go:
          filters:
            tags:
              only: /.*/
      - publish-docker-release:
          requires:
            - build-go
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-github-release:
          requires:
            - build-go
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/